TimeDomain:
  AddNoise:
    csv_file: ./Extracted_Noise/noise.csv
    pad_noise: True
    snr_low: 5
    snr_high: 10
    noise_method: "spectral"  # Options: "repeat", "crossfade", "spectral"

Augmenter:
  parallel_augment: True
  concat_original: False
  min_augmentations: 1
  max_augmentations: 1
  shuffle_augmentations: False
  repeat_augment: 1
